name: Build Docker Image

on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - v*
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7.0.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/openmodelica/build-deps

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: false
